module:
  hugoVersion:
    min: "0.84.0"

params:
  site_logo: "img/practice-room-logo.png"
  show_reading_time: true
  favicon: "img/favicon.ico"
  ananke_socials:
  - name: practace
    url: https://www.practacemusic.com/track
  