module:
  hugoVersion:
    min: "0.84.0"

params:
  site_logo: "img/smallLogo.png"
  featured_image: "img/music.jpg"
  show_reading_time: true
  ananke_socials:
  - name: PractACE App
    url: https://www.practacemusic.com
  