module:
  hugoVersion:
    min: "0.84.0"

params:
  site_logo: "img/practice-room-logo.png"
  show_reading_time: true
  googleAnalytics: "G-96S6RZ59C2"

  favicon: "img/favicon.ico"
  mainSections: 
    - "post"
  ananke_socials:
  - name: practace
    url: https://www.practacemusic.com/track
  